name: Create Zip of Changed Files

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  zip_changed_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get list of changed files
      id: changed_files
      run: |
        git diff --name-only HEAD^ HEAD > changed_files.txt
        cat changed_files.txt

    - name: Copy changed files to a new directory
      run: |
        mkdir -p changed_files
        while IFS= read -r file; do
          if [ -f "$file" ]; then
            mkdir -p "changed_files/$(dirname "$file")"
            cp "$file" "changed_files/$file"
          fi
        done < changed_files.txt

    - name: Zip the changed files
      run: |
        zip -r changed_files.zip changed_files

    - name: Upload zip file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: changed-files
        path: changed_files.zip
