name: Create Zip of Changed Files

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  zip_changed_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get the current commit hash
      id: get_commit
      run: |
        commitHash=$(git rev-parse HEAD)
        echo "Current commit: $commitHash"
        echo "::set-output name=commit::$commitHash"

    - name: Get list of changed files
      id: changed_files
      run: |
        # Check if there are at least two commits
        commitCount=$(git rev-list --count HEAD)
        if [ "$commitCount" -gt 1 ]; then
          git diff --name-only HEAD^ HEAD > changed_files.txt
        else
          echo "No previous commit found. No files changed."
          touch changed_files.txt
        fi
        cat changed_files.txt

    - name: Copy changed files to a new directory
      run: |
        mkdir changed_files
        while IFS= read -r file; do
          if [ -f "$file" ]; then
            destination="changed_files/$(dirname "$file")"
            mkdir -p "$destination"
            cp "$file" "$destination"
          fi
        done < changed_files.txt

    - name: Zip the changed files
      run: zip -r changed_files.zip changed_files -x "changed_files/.github/*"

    - name: Upload zip file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: changed-files
        path: changed_files.zip

