name: Create Zip of Changed Files

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  zip_changed_files:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the current commit hash
      id: get_commit
      run: |
        $commitHash = git rev-parse HEAD
        echo "Current commit: $commitHash"
        echo "::set-output name=commit::$commitHash"

    - name: Get list of changed files in the commit
      id: changed_files
      run: |
        git diff-tree --no-commit-id --name-only -r ${{ steps.get_commit.outputs.commit }} > changed_files.txt
        type changed_files.txt

    - name: Copy changed files to a new directory
      run: |
        mkdir changed_files
        foreach ($file in Get-Content changed_files.txt) {
          if (Test-Path -Path $file) {
            $destination = "changed_files\" + [System.IO.Path]
